import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sourcePath = resolve(root, "design", "design-tokens.json");
const outputPath = resolve(root, "src", "styles", "tokens.css");

const source = JSON.parse(await readFile(sourcePath, "utf8"));

if (!source?.meta?.canonical || !Array.isArray(source.tokens)) {
  throw new Error("design/design-tokens.json must be the canonical token source.");
}

const seen = new Set();
const lines = [
  "/* AUTO-GENERATED by scripts/generate-tokens.mjs.",
  " * Source: design/design-tokens.json.",
  " * Do not edit this file directly.",
  " */",
  ":root {",
  "  color-scheme: dark;",
];

for (const token of source.tokens) {
  if (!token || typeof token.cssVar !== "string" || !token.cssVar.startsWith("--rook-")) {
    throw new Error(`Invalid cssVar: ${JSON.stringify(token)}`);
  }
  if (seen.has(token.cssVar)) {
    throw new Error(`Duplicate cssVar: ${token.cssVar}`);
  }
  if (typeof token.value !== "string" || token.value.length === 0) {
    throw new Error(`Invalid value for ${token.cssVar}`);
  }

  seen.add(token.cssVar);
  lines.push(`  ${token.cssVar}: ${token.value};`);
}

lines.push(
  "}",
  "",
  "@media (prefers-reduced-motion: reduce) {",
  "  *,",
  "  *::before,",
  "  *::after {",
  "    animation-duration: 1ms !important;",
  "    animation-iteration-count: 1 !important;",
  "    scroll-behavior: auto !important;",
  "    transition-duration: 1ms !important;",
  "  }",
  "}",
  "",
);

await writeFile(outputPath, lines.join("\n"), "utf8");
console.log(`Generated ${outputPath} from ${source.tokens.length} canonical tokens.`);
